#!/usr/bin/env python3
"""Generates MANA's NCCL glue from nccl.h (see README).

  gen-nccl-wrappers.py thunks  NCCL_H                > nccl_lh_thunks.cpp
  gen-nccl-wrappers.py forward NCCL_H WRAPPERS_C     > nccl_forward.c
  gen-nccl-wrappers.py stub    NAMES_FILE            > nccl_stub.c

thunks:  for each function ncclX of nccl.h, mana_lh_ncclX(): calls the lower
         half's ncclX (resolved by name on first use) with the lower half's FS.
forward: for each function of nccl.h that WRAPPERS_C (the checkpointing
         wrappers) does not define, ncclX() calls mana_lh_ncclX().  One that
         takes a communicator refuses a virtual one: real NCCL would get a
         handle it does not know.
stub:    the upper half's libnccl: every name in NAMES_FILE (the real
         library's exported functions), aborting.  libmana.so, which is
         preloaded, defines the functions that are called.
"""

import re
import sys

# Not part of the API (a macro on some systems): left to the stub.
SKIP = {"ncclResetDebugInit"}

DECL = re.compile(r"^\s*(ncclResult_t|const char\s*\*|void)\s*(nccl\w+)\s*\(")


def declarations(header):
  """(return type, name, [(type, name)]) of each nccl* function."""
  lines = open(header).read().split("\n")
  out = []
  seen = set()
  i = 0
  while i < len(lines):
    m = DECL.match(lines[i])
    if not m:
      i += 1
      continue
    text = lines[i]
    while ";" not in text and i + 1 < len(lines):
      i += 1
      text += " " + lines[i].strip()
    i += 1
    ret = re.sub(r"\s+", " ", m.group(1)).replace(" *", "*")
    name = m.group(2)
    params = text[text.index("(", m.end() - 1) + 1:text.rindex(")")].strip()
    if name in seen or name in SKIP:
      continue
    seen.add(name)
    out.append((ret, name, parse_params(params)))
  return out


def parse_params(params):
  if params in ("", "void"):
    return []
  result = []
  for p in params.split(","):
    p = p.strip()
    m = re.match(r"^(.*?)(\w+)$", p)
    ptype, pname = m.group(1).strip(), m.group(2)
    result.append((ptype, pname))
  return result


def proto(params):
  return ", ".join("%s %s" % p for p in params) if params else "void"


def args(params):
  return ", ".join(n for _, n in params)


def failure(ret, name):
  if ret == "ncclResult_t":
    return "ncclInternalError"
  if ret == "const char*":
    return '"MANA: %s is not available in the lower half"' % name
  return ""


def thunks(header):
  decls = declarations(header)
  print("// Generated by gen-nccl-wrappers.py from %s: do not edit." % header)
  print('#include "nccl_lh.h"')
  print()
  print("static const char *const lh_names[] = {")
  for _, name, _ in decls:
    print('  "%s",' % name)
  print("};")
  print("#define N_LH_FNS %d" % len(decls))
  print("static void *lh_fns[N_LH_FNS];")
  print()
  print("static int")
  print("lh_index(const char *name)")
  print("{")
  print("  for (int i = 0; i < N_LH_FNS; i++) {")
  print("    if (strcmp(lh_names[i], name) == 0) {")
  print("      return i;")
  print("    }")
  print("  }")
  print("  return -1;")
  print("}")
  print()
  print("// The lower half's function i, or NULL if its NCCL has none.")
  print("static void *")
  print("lh_fn(int i)")
  print("{")
  print("  void *fn = __atomic_load_n(&lh_fns[i], __ATOMIC_ACQUIRE);")
  print("  if (fn == NULL) {")
  print("    fn = mana_nccl_lh_dlsym(lh_names[i]);")
  print("    if (fn == NULL) {")
  print("      fn = MANA_NCCL_MISSING;")
  print("    }")
  print("    __atomic_store_n(&lh_fns[i], fn, __ATOMIC_RELEASE);")
  print("  }")
  print("  return fn == MANA_NCCL_MISSING ? NULL : fn;")
  print("}")
  print()
  print('extern "C" void')
  print("mana_nccl_reset_lh_fns(void)")
  print("{")
  print("  for (int i = 0; i < N_LH_FNS; i++) {")
  print("    lh_fns[i] = NULL;")
  print("  }")
  print("}")
  print()
  thunk_names = []
  for ret, name, params in decls:
    thunk = "mana_lh_" + name
    thunk_names.append((name, thunk))
    print('extern "C" %s' % ret)
    print("%s(%s)" % (thunk, proto(params)))
    print("{")
    print("  typedef %s (*fn_t)(%s);" % (ret, proto(params)))
    print("  // The gate first: at restart, the lower half's functions are")
    print("  // found again once the lower half is open.")
    print("  int gated = mana_nccl_gate_enter();")
    print("  fn_t fn = (fn_t)lh_fn(%d);" % (len(thunk_names) - 1))
    print("  if (fn == NULL) {")
    print("    mana_nccl_gate_leave(gated);")
    print('    mana_nccl_missing("%s");' % name)
    f = failure(ret, name)
    print("    return%s;" % (" " + f if f else ""))
    print("  }")
    if ret != "void":
      print("  %s ret;" % ret)
    print("  JUMP_TO_LOWER_HALF(lh_info->fsaddr);")
    print("  %sfn(%s);" % ("ret = " if ret != "void" else "", args(params)))
    print("  RETURN_TO_UPPER_HALF();")
    print("  mana_nccl_gate_leave(gated);")
    if ret != "void":
      print("  return ret;")
    print("}")
    print()
  print("// The thunk of 'name', if the lower half's NCCL has 'name'; else NULL.")
  print('extern "C" void *')
  print("mana_nccl_real_dlsym(const char *name)")
  print("{")
  print("  int i = lh_index(name);")
  print("  if (i < 0 || lh_fn(i) == NULL) {")
  print("    return NULL;")
  print("  }")
  print("  switch (i) {")
  for i, (_, thunk) in enumerate(thunk_names):
    print("    case %d: return (void *)&%s;" % (i, thunk))
  print("  }")
  print("  return NULL;")
  print("}")


def wrapped(source):
  names = set()
  for line in open(source):
    m = re.match(r"^(?:ncclResult_t|const char \*)\s*(nccl\w+)\(", line)
    if m:
      names.add(m.group(1))
  return names


def forward(header, source):
  done = wrapped(source)
  decls = declarations(header)
  print("// Generated by gen-nccl-wrappers.py from %s: do not edit." % header)
  print("// The NCCL functions that %s does not define." % source)
  print('#include "nccl_lh.h"')
  print('#include "vcomm.h"')
  print()
  for ret, name, params in decls:
    if name in done:
      continue
    print("%s mana_lh_%s(%s);" % (ret, name, proto(params)))
    print()
    print("%s" % ret)
    print("%s(%s)" % (name, proto(params)))
    print("{")
    comms = [n for t, n in params if t.replace("const ", "") == "ncclComm_t"]
    for c in comms:
      print("  if (vcomm_lookup(%s) != NULL) {" % c)
      print('    mana_nccl_refuse("%s");' % name)
      print("    return %s;" % (failure(ret, name) if ret != "ncclResult_t"
                                else "ncclInvalidUsage"))
      print("  }")
    print("  %smana_lh_%s(%s);" % ("return " if ret != "void" else "", name,
                                   args(params)))
    print("}")
    print()


def stub(names_file):
  names = sorted(set(open(names_file).read().split()))
  print("// Generated by gen-nccl-wrappers.py: do not edit.")
  print("// The upper half's libnccl (see README): its functions are never")
  print("// called, since libmana.so defines them and is loaded first.")
  print("#include <stdio.h>")
  print("#include <stdlib.h>")
  print()
  print("int mana_nccl_stub = 1;")
  print()
  print("static void")
  print("stub_called(const char *name)")
  print("{")
  print('  fprintf(stderr, "MANA: %s() of the NCCL stub was called; MANA does "')
  print('          "not support it\\n", name);')
  print("  abort();")
  print("}")
  print()
  for name in names:
    print('void %s(void) { stub_called("%s"); }' % (name, name))


if __name__ == "__main__":
  if sys.argv[1] == "thunks":
    thunks(sys.argv[2])
  elif sys.argv[1] == "forward":
    forward(sys.argv[2], sys.argv[3])
  elif sys.argv[1] == "stub":
    stub(sys.argv[2])
  else:
    sys.exit(__doc__)
