/*
 * Runtime of MANA's forwarding shims (libmana_fwd.so, in the lower half).
 *
 * The CUDA checkpoint API supports one CUDA driver per process, and it must
 * be the upper half's: the lower half is replaced at restart.  So the lower
 * half's MPI (UCX, MPICH/yaksa, NCCL) is given shims of libcuda.so.1 and
 * libcudart.so.13 whose every symbol forwards to the upper half's library.
 * The MPI then works on the application's device memory, in the same CUDA
 * context, as a CUDA-aware MPI does natively.
 *
 * A forwarded call runs the upper half's code, so it must run with the upper
 * half's FS register (its TLS): the trampolines in the shims (generated by
 * gen-forward-shim.py) call fwd_enter(), switch FS, and jump to the target;
 * the target returns to fwd_return, which switches FS back.  Each upper-half
 * thread registers its FS (mana_fwd_register_thread(), from MANA's
 * JUMP_TO_LOWER_HALF); all of them share the lower half's main TLS while in
 * the lower half, so the per-thread state here is keyed by the kernel tid.
 */

#define _GNU_SOURCE
#include <asm/prctl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

#include "fwd-runtime.h"

#define MAX_THREADS 256
#define MAX_DEPTH 16
#define MAX_DYN_SLOTS 4096

typedef struct {
  volatile int tid;           // 0: free
  unsigned long uhfs;         // 0: no upper half (a lower-half thread)
  unsigned long stack_lo, stack_hi;   // its stack, if known
  int depth;
  FwdRecord recs[MAX_DEPTH];
} FwdThread;

// The threads with a known stack, to find a thread by its stack pointer:
// no system call (gettid) in the common path of a forwarded call.
static FwdThread *by_stack[MAX_THREADS];
static volatile int n_by_stack;

static FwdThread threads[MAX_THREADS];
FwdCtl mana_fwd_ctl;
int mana_fwd_fsgsbase = 0;    // Read by the trampolines.
static int verbose = -1;

static long
raw_syscall2(long nr, long a, long b)
{
  long ret;
  asm volatile("syscall" : "=a"(ret) : "0"(nr), "D"(a), "S"(b)
               : "rcx", "r11", "memory");
  return ret;
}

static int
fwd_gettid(void)
{
  long ret;
  asm volatile("syscall" : "=a"(ret) : "0"(SYS_gettid) : "rcx", "r11", "memory");
  return (int)ret;
}

static unsigned long
fwd_getfs(void)
{
  unsigned long fs;
  if (mana_fwd_fsgsbase) {
    asm volatile("rdfsbase %0" : "=r"(fs));
  } else {
    raw_syscall2(SYS_arch_prctl, ARCH_GET_FS, (long)&fs);
  }
  return fs;
}

static void
fwd_setfs(unsigned long fs)
{
  if (mana_fwd_fsgsbase) {
    asm volatile("wrfsbase %0" : : "r"(fs) : "memory");
  } else {
    raw_syscall2(SYS_arch_prctl, ARCH_SET_FS, (long)fs);
  }
}

static void
fwd_log(const char *fmt, const char *a, const char *b)
{
  if (verbose < 0) {
    const char *v = getenv("MANA_FWD_VERBOSE");
    verbose = v != NULL && v[0] != '0';
  }
  if (verbose) {
    char buf[512];
    int n = snprintf(buf, sizeof buf, "[mana-fwd %d] ", fwd_gettid());
    n += snprintf(buf + n, sizeof buf - n, fmt, a, b);
    if (n > 0) {
      if (write(2, buf, n < (int)sizeof buf ? n : (int)sizeof buf - 1) < 0) {
        return;
      }
    }
  }
}

static FwdThread *
find_thread(int tid, int create)
{
  unsigned h = (unsigned)tid % MAX_THREADS;
  for (int i = 0; i < MAX_THREADS; i++) {
    FwdThread *t = &threads[(h + i) % MAX_THREADS];
    if (t->tid == tid) {
      return t;
    }
    if (t->tid == 0) {
      if (!create) {
        return NULL;
      }
      if (__sync_bool_compare_and_swap(&t->tid, 0, tid)) {
        return t;
      }
      if (t->tid == tid) {
        return t;
      }
    }
  }
  return NULL;
}

void
mana_fwd_register_thread(int tid, unsigned long uhfs)
{
  FwdThread *t = find_thread(tid, 1);
  if (t != NULL) {
    t->uhfs = uhfs;
  }
}

// Also records the thread's stack [lo, hi).  A thread that the lower half
// creates (e.g. UCX's) has its stack elsewhere, and is found by its tid.
void
mana_fwd_register_thread_stack(int tid, unsigned long uhfs,
                               unsigned long lo, unsigned long hi)
{
  FwdThread *t = find_thread(tid, 1);
  if (t == NULL) {
    return;
  }
  t->uhfs = uhfs;
  if (lo >= hi) {
    return;
  }
  // A dead thread's stack may be reused by this one: drop its entries.
  for (int i = 0; i < n_by_stack; i++) {
    FwdThread *o = by_stack[i];
    if (o != t && o->stack_lo < hi && lo < o->stack_hi) {
      o->stack_lo = o->stack_hi = 0;
    }
  }
  t->stack_lo = lo;
  t->stack_hi = hi;
  for (int i = 0; i < n_by_stack; i++) {
    if (by_stack[i] == t) {
      return;
    }
  }
  if (n_by_stack < MAX_THREADS) {
    by_stack[n_by_stack] = t;
    __atomic_store_n(&n_by_stack, n_by_stack + 1, __ATOMIC_RELEASE);
  }
}

static inline FwdThread *
thread_by_stack(unsigned long sp)
{
  int n = __atomic_load_n(&n_by_stack, __ATOMIC_ACQUIRE);
  for (int i = 0; i < n; i++) {
    FwdThread *t = by_stack[i];
    if (sp >= t->stack_lo && sp < t->stack_hi) {
      return t;
    }
  }
  return NULL;
}

static inline FwdThread *
current_thread(unsigned long sp, int create)
{
  FwdThread *t = thread_by_stack(sp);
  return t != NULL ? t : find_thread(fwd_gettid(), create);
}

void
mana_fwd_forget_threads(void)
{
  n_by_stack = 0;
  memset(threads, 0, sizeof threads);
}

// The value returned by a call that cannot be forwarded: CUresult and
// cudaError_t both say "no device" with 100.
static long
fwd_unavailable(void)
{
  return 100;
}

static void *
resolve(FwdLib *lib, int idx, unsigned long uhfs, unsigned long lhfs)
{
  void *target = lib->targets[idx];
  if (target != NULL) {
    return target;
  }
  if (mana_fwd_ctl.uh_dlsym == NULL || uhfs == 0) {
    return NULL;
  }
  if (!lib->upper_seen) {
    lib->upper_seen = 1;
    if (lib->on_upper != NULL) {
      lib->on_upper();
    }
  }
  // The resolver is upper-half code (dlopen/dlsym of the upper half).
  fwd_setfs(uhfs);
  target = mana_fwd_ctl.uh_dlsym(lib->soname, lib->names[idx]);
  fwd_setfs(lhfs);
  if (target == NULL) {
    fwd_log("cannot resolve %s in the upper half's %s\n",
            lib->names[idx], lib->soname);
  } else {
    fwd_log("forwarding %s (%s)\n", lib->names[idx], lib->soname);
  }
  lib->targets[idx] = target;
  return target;
}

static unsigned long n_calls;

__attribute__((destructor)) static void
fwd_report(void)
{
  if (getenv("MANA_FWD_VERBOSE")) {
    char buf[128];
    int n = snprintf(buf, sizeof buf, "[mana-fwd %d] %lu forwarded calls\n",
                     fwd_gettid(), n_calls);
    if (write(2, buf, n) < 0) {
      return;
    }
  }
}

unsigned long
mana_fwd_calls(void)
{
  return n_calls;
}

FwdRecord *
mana_fwd_enter(FwdLib *lib, long idx, void **retslot)
{
  n_calls++;
  FwdThread *t = current_thread((unsigned long)retslot, 1);
  unsigned long lhfs = fwd_getfs();
  if (t == NULL || t->depth >= MAX_DEPTH) {
    fprintf(stderr, "[mana-fwd %d] FATAL: thread table full or calls nested "
            "too deep (%s)\n", fwd_gettid(), lib->names[idx]);
    abort();
  }
  FwdRecord *r = &t->recs[t->depth++];
  r->ret = *retslot;
  r->lhfs = lhfs;
  void *target = resolve(lib, (int)idx, t->uhfs, lhfs);
  if (target == NULL || t->uhfs == 0) {
    if (t->uhfs == 0) {
      fwd_log("%s called on a thread without an upper half (%s)\n",
              lib->names[idx], lib->soname);
    }
    r->target = (void *)fwd_unavailable;
    r->uhfs = lhfs;           // No FS switch.
  } else {
    r->target = target;
    r->uhfs = t->uhfs;
  }
  return r;
}

void
mana_fwd_exit(FwdRecord *r)
{
  // The record is in its thread's FwdThread.
  FwdThread *t = &threads[((char *)r - (char *)threads) / sizeof(FwdThread)];
  if (t->depth > 0 && &t->recs[t->depth - 1] == r) {
    t->depth--;
  }
}

// Calls 'fn' (upper-half code) with this thread's upper-half FS; for the C
// wrappers of the shims.  Returns 0 if there is no upper half for this thread.
unsigned long
mana_fwd_uhfs(void)
{
  int here;
  FwdThread *t = current_thread((unsigned long)&here, 0);
  return t != NULL ? t->uhfs : 0;
}

void
mana_fwd_switch(unsigned long fs)
{
  fwd_setfs(fs);
}

unsigned long
mana_fwd_current_fs(void)
{
  return fwd_getfs();
}

// Upper-half function pointers given to the lower half (cuGetProcAddress,
// cudaGetDriverEntryPoint) must be called through a trampoline, too:
// dynamic slots of the 'dyn' library, defined in fwd-dyn.S.
static const char *dyn_names[MAX_DYN_SLOTS];
static void *dyn_targets[MAX_DYN_SLOTS];
__attribute__((visibility("hidden")))
FwdLib mana_fwd_dyn_lib = { "(dynamic)", dyn_names, dyn_targets, MAX_DYN_SLOTS, NULL, 0 };
extern char mana_fwd_dyn_tramp[];   // MAX_DYN_SLOTS entries, 16 bytes each
static int n_dyn = 0;

void *
mana_fwd_wrap_ptr(void *upper_fn, const char *name)
{
  if (upper_fn == NULL) {
    return NULL;
  }
  for (int i = 0; i < n_dyn; i++) {
    if (mana_fwd_dyn_lib.targets[i] == upper_fn) {
      return mana_fwd_dyn_tramp + 16 * i;
    }
  }
  if (n_dyn >= MAX_DYN_SLOTS) {
    fprintf(stderr, "[mana-fwd] FATAL: out of dynamic trampolines\n");
    abort();
  }
  int i = n_dyn;
  mana_fwd_dyn_lib.names[i] = strdup(name != NULL ? name : "(pointer)");
  mana_fwd_dyn_lib.targets[i] = upper_fn;
  __sync_synchronize();
  n_dyn++;
  return mana_fwd_dyn_tramp + 16 * i;
}

FwdCtl *
mana_fwd_get_ctl(void)
{
  return &mana_fwd_ctl;
}

// Set by the libcuda shim (cuda-special.c), which knows the CUDA calls.
void (*mana_fwd_cuda_before_ckpt)(void);
void (*mana_fwd_cuda_after_resume)(void);
void (*mana_fwd_cuda_after_resume_peers)(void);

static void
fwd_after_resume_peers(void)
{
  if (mana_fwd_cuda_after_resume_peers != NULL) {
    mana_fwd_cuda_after_resume_peers();
  }
}

static void
fwd_before_ckpt(void)
{
  if (mana_fwd_cuda_before_ckpt != NULL) {
    mana_fwd_cuda_before_ckpt();
  }
}

static void
fwd_after_resume(void)
{
  if (mana_fwd_cuda_after_resume != NULL) {
    mana_fwd_cuda_after_resume();
  }
}

__attribute__((constructor)) static void
fwd_runtime_init(void)
{
  mana_fwd_ctl.before_ckpt = fwd_before_ckpt;
  mana_fwd_ctl.after_resume = fwd_after_resume;
  mana_fwd_ctl.after_resume_peers = fwd_after_resume_peers;
  mana_fwd_ctl.register_thread = mana_fwd_register_thread;
  mana_fwd_ctl.register_thread_stack = mana_fwd_register_thread_stack;
  mana_fwd_ctl.forget_threads = mana_fwd_forget_threads;
  mana_fwd_ctl.fsgsbase = &mana_fwd_fsgsbase;
}

/*
 * Private function tables (cuGetExportTable, nvmlInternalGetExportTable):
 * returns a copy of 'table' whose entries that point into the code of the
 * library containing 'lib_fn' (an upper-half function) are trampolines.  The
 * first word of a table is its size in bytes.
 */
#include <fcntl.h>

typedef struct { unsigned long lo, hi; } Range;

// The executable mappings of the file that contains address 'a'.
static int
code_ranges(unsigned long a, Range *ranges, int max)
{
  int n = 0;
  int fd = open("/proc/self/maps", O_RDONLY);
  if (fd < 0) {
    return 0;
  }
  char buf[1 << 16], line[1024], path[512] = "";
  for (int pass = 0; pass < 2; pass++) {
    lseek(fd, 0, SEEK_SET);
    ssize_t nr, len = 0;
    while ((nr = read(fd, buf, sizeof buf)) > 0) {
      for (ssize_t i = 0; i < nr; i++) {
        if (buf[i] != '\n') {
          if (len < (ssize_t)sizeof line - 1) line[len++] = buf[i];
          continue;
        }
        line[len] = '\0';
        len = 0;
        unsigned long lo, hi;
        char perms[8], p[512] = "";
        if (sscanf(line, "%lx-%lx %7s %*s %*s %*s %511s", &lo, &hi, perms, p) < 3) {
          continue;
        }
        if (pass == 0 && a >= lo && a < hi) {
          strcpy(path, p);
        } else if (pass == 1 && perms[2] == 'x' && path[0] &&
                   strcmp(p, path) == 0 && n < max) {
          ranges[n].lo = lo;
          ranges[n].hi = hi;
          n++;
        }
      }
    }
  }
  close(fd);
  return n;
}

typedef struct { const void *real; void *copy; } Table;
static Table tables[128];
static int n_tables;

const void *
mana_fwd_wrap_table(const void *table, void *lib_fn, const void *uuid)
{
  for (int i = 0; i < n_tables; i++) {
    if (tables[i].real == table) {
      return tables[i].copy;
    }
  }
  unsigned long size = *(const unsigned long *)table;
  if (size < 8 || size > 65536 || size % 8 != 0 || n_tables == 128) {
    fprintf(stderr, "[mana-fwd] export table with first word %lu: "
            "not wrapped\n", size);
    return table;
  }
  Range code[16];
  int n_code = code_ranges((unsigned long)lib_fn, code, 16);
  unsigned long *copy = (unsigned long *)malloc(size);
  memcpy(copy, table, size);
  int wrapped = 0;
  for (unsigned long i = 1; i < size / 8; i++) {
    for (int j = 0; j < n_code; j++) {
      if (copy[i] >= code[j].lo && copy[i] < code[j].hi) {
        copy[i] = (unsigned long)mana_fwd_wrap_ptr((void *)copy[i],
                                                   "(export table)");
        wrapped++;
        break;
      }
    }
  }
  const unsigned char *u = (const unsigned char *)uuid;
  char msg[160];
  snprintf(msg, sizeof msg, "export table %02x%02x%02x%02x...: %lu bytes, "
           "%d of %lu entries wrapped\n", u[0], u[1], u[2], u[3], size,
           wrapped, size / 8 - 1);
  fwd_log("%s%s", msg, "");
  tables[n_tables].real = table;
  tables[n_tables].copy = copy;
  n_tables++;
  return copy;
}
