#!/usr/bin/env python3
"""Generate a forwarding shim of a shared library for MANA's lower half.

  gen-forward-shim.py REAL_LIB SONAME PREFIX OUT_DIR [EXCLUDED_SYMBOL ...]

For every function that REAL_LIB exports, the shim (OUT_DIR/PREFIX-tramp.S,
OUT_DIR/PREFIX-desc.c) defines a trampoline that forwards the call to the
same symbol of SONAME in the upper half (see fwd-runtime.c, fwd-tramp.inc).
Exported data symbols get dummies.  EXCLUDED_SYMBOLs get no trampoline: a
hand-written C wrapper defines them (e.g. cuGetProcAddress, whose results
must be wrapped, too).
"""
import os
import subprocess
import sys

real, soname, prefix, out_dir = sys.argv[1:5]
excluded = set(sys.argv[5:])

# readelf, not nm: some nm builds (SUSE's binutils 2.45) do not print symbol
# versions, and the shim must have the real library's.  A line is
#   NUM: VALUE SIZE TYPE BIND VISIBILITY [NOTES] NDX NAME[@[@]VERSION] [(IDX)]
syms = subprocess.run(["readelf", "-W", "--dyn-syms", real],
                      stdout=subprocess.PIPE, universal_newlines=True,
                      check=True).stdout
funcs, data = [], []
versions = {}                 # version node -> symbols
for line in syms.splitlines():
  parts = line.split()
  if parts and parts[-1].startswith("(") and parts[-1].endswith(")"):
    parts = parts[:-1]        # the version index
  if len(parts) < 8 or not parts[0].endswith(":"):
    continue
  kind, bind, ndx, full = parts[3], parts[4], parts[-2], parts[-1]
  if ndx in ("UND", "ABS") or bind == "LOCAL":
    continue
  name = full.split("@")[0]
  if "@@" in full:
    versions.setdefault(full.split("@@")[1], []).append(name)
  if name in excluded or name in funcs or name in data:
    continue
  if kind in ("FUNC", "IFUNC"):
    funcs.append(name)
  elif kind == "OBJECT":
    data.append(name)

desc = "mana_fwd_%s_lib" % prefix
with open(os.path.join(out_dir, prefix + "-tramp.S"), "w") as f:
  f.write("/* Generated by gen-forward-shim.py from %s. */\n" % real)
  f.write('#include "fwd-tramp.inc"\n\n')
  f.write("FWD_COMMON %s, fwd_%s_common, fwd_%s_ret\n\n" % (desc, prefix, prefix))
  for i, name in enumerate(funcs):
    f.write("FWD_SLOT %s, %d, fwd_%s_common\n" % (name, i, prefix))
  f.write('\n  .section .note.GNU-stack,"",@progbits\n')

with open(os.path.join(out_dir, prefix + "-desc.c"), "w") as f:
  f.write("/* Generated by gen-forward-shim.py from %s. */\n" % real)
  f.write('#include "fwd-runtime.h"\n\n')
  f.write("static const char *names[] = {\n")
  for name in funcs:
    f.write('  "%s",\n' % name)
  f.write("};\n")
  f.write("static void *targets[%d];\n" % len(funcs))
  f.write("void mana_fwd_%s_on_upper(void) __attribute__((weak));\n" % prefix)
  f.write('__attribute__((visibility("hidden")))\n')
  f.write('FwdLib %s = { "%s", names, targets, %d, mana_fwd_%s_on_upper, 0 };\n\n'
          % (desc, soname, len(funcs), prefix))
  for name in data:
    f.write("char %s[64];\n" % name)
# The shim's symbols get the real library's (default) versions, so that
# programs linked with versioned symbols find them.
with open(os.path.join(out_dir, prefix + ".map"), "w") as f:
  if versions:
    for node, names in versions.items():
      f.write("%s {\n  global:\n" % node)
      for name in sorted(set(names)):
        f.write("    %s;\n" % name)
      f.write("};\n")
  else:
    f.write("{ global: *; };\n")
print("%s: %d functions, %d data symbols, %d excluded"
      % (prefix, len(funcs), len(data), len(excluded)))
