#!/usr/bin/env python3
"""Generate a forwarding shim of a shared library for MANA's lower half.

  gen-forward-shim.py REAL_LIB SONAME PREFIX OUT_DIR [EXCLUDED_SYMBOL ...]

For every function that REAL_LIB exports, the shim (OUT_DIR/PREFIX-tramp.S,
OUT_DIR/PREFIX-desc.c) defines a trampoline that forwards the call to the
same symbol of SONAME in the upper half (see fwd-runtime.c, fwd-tramp.inc).
Exported data symbols get dummies.  EXCLUDED_SYMBOLs get no trampoline: a
hand-written C wrapper defines them (e.g. cuGetProcAddress, whose results
must be wrapped, too).
"""
import os
import subprocess
import sys

real, soname, prefix, out_dir = sys.argv[1:5]
excluded = set(sys.argv[5:])

nm = subprocess.run(["nm", "-D", "--defined-only", real],
                    capture_output=True, text=True, check=True).stdout
funcs, data = [], []
versions = {}                 # version node -> symbols
for line in nm.splitlines():
  parts = line.split()
  if len(parts) != 3:
    continue
  kind, name = parts[1], parts[2].split("@")[0]
  if "@@" in parts[2]:
    versions.setdefault(parts[2].split("@@")[1], []).append(name)
  if name in excluded or name in funcs or name in data:
    continue
  if kind in ("T", "W", "i"):
    funcs.append(name)
  elif kind in ("B", "D", "V", "R"):
    data.append(name)

desc = "mana_fwd_%s_lib" % prefix
with open(os.path.join(out_dir, prefix + "-tramp.S"), "w") as f:
  f.write("/* Generated by gen-forward-shim.py from %s. */\n" % real)
  f.write('#include "fwd-tramp.inc"\n\n')
  f.write("FWD_COMMON %s, fwd_%s_common, fwd_%s_ret\n\n" % (desc, prefix, prefix))
  for i, name in enumerate(funcs):
    f.write("FWD_SLOT %s, %d, fwd_%s_common\n" % (name, i, prefix))
  f.write('\n  .section .note.GNU-stack,"",@progbits\n')

with open(os.path.join(out_dir, prefix + "-desc.c"), "w") as f:
  f.write("/* Generated by gen-forward-shim.py from %s. */\n" % real)
  f.write('#include "fwd-runtime.h"\n\n')
  f.write("static const char *names[] = {\n")
  for name in funcs:
    f.write('  "%s",\n' % name)
  f.write("};\n")
  f.write("static void *targets[%d];\n" % len(funcs))
  f.write("void mana_fwd_%s_on_upper(void) __attribute__((weak));\n" % prefix)
  f.write('__attribute__((visibility("hidden")))\n')
  f.write('FwdLib %s = { "%s", names, targets, %d, mana_fwd_%s_on_upper, 0 };\n\n'
          % (desc, soname, len(funcs), prefix))
  for name in data:
    f.write("char %s[64];\n" % name)
# The shim's symbols get the real library's (default) versions, so that
# programs linked with versioned symbols find them.
with open(os.path.join(out_dir, prefix + ".map"), "w") as f:
  if versions:
    for node, names in versions.items():
      f.write("%s {\n  global:\n" % node)
      for name in sorted(set(names)):
        f.write("    %s;\n" % name)
      f.write("};\n")
  else:
    f.write("{ global: *; };\n")
print("%s: %d functions, %d data symbols, %d excluded"
      % (prefix, len(funcs), len(data), len(excluded)))
